### PR TITLE
validate SHA1 of important files

### PR DESCRIPTION
**Pull request by mikeryan**
Currently only validating pifdata.bin. Probably also worth validating DD
IPL and other known binaries.

### CODE REVIEW

**Comment by tj90241** [comment]
<@krom> mikeryan: did you implement correct pif sha1 for euro & ntsc pif?

This is a good point: we don't want to block PAL, as it works now. I don't own that ROM image, so I don't know the hash for the file.

**Comment by vgturtle127** [comment]
@mikeryan @tj90241 So how many total things will this verify when complete?

I think the NTSC, NTSC-J, and PAL pif should be checked along with the N64DD IPL. Those are all I can think of, though.

**Comment by mikeryan** [comment]
I've pushed a commit to validate the PAL PIF and I can validate the DD
IPL in another commit this evening. Can anyone provide a SHA1 of the
NTSC-J PIFROM, assuming it actually varies from NTSC?

**Comment by vgturtle127** [comment]
@mikeryan Here is what I have:

PAL PIFROM:
SHA-1: 46CAE59D31F9298B93F3380879454FCEF54EE6CC

NTSC PIFROM:
SHA-1: 3A23E4CCCCA2CAD62A83EEA8519C7184FE1F7BE2

NTSC-J PIFROM:
SHA-1: 9174EADC0F0EA2654C95FD941406AB46B9DC9BDD

64DD IPL:
SHA-1: BF861922DCB78C316360E3E742F4F70FF63C9BC3

These might be wrong, I am not sure if they were dumped correctly or not. Since we don't really have a method of verifying if they are complete or not.

I also have these:

NORMPNT.ROM
SHA-1: C27B4A364A24DAEEE6E99FD286753FD6216362B4

NORMSLP.ROM
SHA-1: EAB43F8CC52C8551D9CFF6FCED18EF80EABA6F05

Not sure what they are for, maybe *somebody* knows?

**Comment by mikeryan** [comment]
@tj90241 that covers all PIFROM variants + DD IPL.

**Comment by vgturtle127** [comment]
@tj90241 @mikeryan Ever seen those last two? I can't figure out what they are for...

**Comment by mikeryan** [comment]
I know they're included in the MAME ROM set but not sure what they're used for. Possibly Aleck64?

**Comment by mikeryan** [comment]
Per Zoinkity, those are the RDP point and slope info. Not sure why they're not needed by cen64 or why they're required by MAME.

**Comment by vgturtle127** [comment]
@mikeryan Point and slope info? Weird.

They are ROM files, so I assumed they were something attached to the system.

**Comment by tj90241** [comment]
angrylion's RDP computes them on the fly.

The RSP division lookup table is integrated into the source.

I don't think you can slap a copyright on either of those things. If I'm in the wrong, let me know and out they go.

**Pull request merged**
